# Generated by Django 4.2.26 on 2025-12-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='storage_limit',
            field=models.PositiveIntegerField(default=1073741824),
        ),
    ]
