# Generated by Django 4.2.26 on 2025-12-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
